-- ============================================
-- BLOG GÜNCELLEMELERİ - PARÇA 5/6
-- Blog 21-25: Detaylı içerikler ve konuya uygun resimler
-- ============================================
-- Bu SQL dosyasını Supabase Dashboard > SQL Editor'de çalıştırın

-- 21. AŞILI FİDE KULLANIMI
UPDATE blogs SET
  excerpt = 'Aşılı fidenin avantajları nelerdir? Daha dayanıklı ve verimli üretim için aşılı fide kullanımı, dikim teknikleri ve bakım yöntemleri hakkında detaylı bilgiler.',
  content = '<h2>Aşılı Fide Kullanımı: Dayanıklılık ve Verim Artışı</h2><p>Aşılı fideler, özel tekniklerle geliştirilmiş, daha dayanıklı ve verimli bitkilerdir. Aşılama tekniği, iki farklı bitki parçasını birleştirerek her ikisinin de en iyi özelliklerini bir araya getirir. Bu rehberde aşılı fide kullanımı hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Aşılı Fidenin Avantajları</h3><p><strong>Hastalıklara daha dayanıklı:</strong> Aşılı fideler güçlü kök sistemine sahip olduğu için toprak kaynaklı hastalıklara karşı daha dirençlidir. Fusarium, Verticillium gibi solgunluk hastalıklarına karşı koruma sağlar. Kök sistemi gelişmiş ve dayanıklı olduğu için bitki sağlığı artar.</p><p><strong>Daha yüksek verim:</strong> Güçlü kök sistemi bitkinin besin ve su alımını artırır, bu da daha fazla meyve üretimine yol açar. Verim artışı %20-30''a kadar çıkabilir. Erken ürün alımı sağlar ve hasat süresi uzar.</p><p><strong>Kök sistemi daha güçlü:</strong> Aşılı fidelerin kök sistemi çok daha gelişmiş ve güçlüdür. Bu sayede topraktan daha iyi besin alır ve daha sağlıklı büyür. Kök çürümesi riski azalır.</p><p><strong>Daha uzun ömür:</strong> Aşılı fideler normal fidelerden daha uzun süre verimli kalır. Özellikle domates ve biber gibi bitkilerde bu avantaj belirgindir. Tek bir bitkiden daha fazla sezon ürün alabilirsiniz.</p><h3>Dikim Teknikleri: Kritik Nokta</h3><p>Aşılı fideleri dikerken aşı noktasını toprak üzerinde bırakın. Bu nokta toprağa gömülmemelidir. Aşı noktası toprağa gömülürse köklenme olur ve aşının amacı kaybolur. Aşı noktası genellikle bitki gövdesinde belirgin bir şişkinlik veya yara izi gibi görünür. Dikim sırasında bu noktayı 2-3 cm toprak üzerinde bırakın. Dikim derinliği normal fidelerden daha az olmalıdır. Kök sistemine dikkat edin ve zarar vermeyin. Dikim sonrası bolca su verin ve ilk hafta dikkatli bakım yapın.</p><h3>Bakım ve Özel Gereksinimler</h3><p>Normal fideler gibi bakım yapın. Aşılı fideler daha dayanıklı olduğu için daha az ilaç gerektirir. Gübreleme normal fideler gibi yapılabilir ancak kök sistemi güçlü olduğu için besin alımı daha iyidir. Aşılı fidelerin yan filizleri de normal fideler gibi budanabilir. Destek sistemleri kurulmalıdır çünkü aşılı fideler daha hızlı büyür. Düzenli sulama önemlidir ancak kök sistemi güçlü olduğu için su stresine karşı daha dayanıklıdırlar. Aşılı fideler için özel bir bakım gerekmez, normal bahçecilik uygulamaları yeterlidir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2070'
WHERE slug = 'asili-fide-kullanimi-avantajlari-ve-dikkat-edilecekler';

-- 22. FİDE ÇOĞALTMA TEKNİKLERİ
UPDATE blogs SET
  excerpt = 'Fide nasıl çoğaltılır? Tohumdan fide üretimi, çelik alma yöntemleri, bölme teknikleri ve fide çoğaltma süreçleri hakkında detaylı rehber. Ekonomik ve keyifli üretim.',
  content = '<h2>Fide Çoğaltma Yöntemleri: Kendi Fidelerinizi Üretin</h2><p>Kendi fidelerinizi üretmek hem ekonomik hem de keyiflidir. Doğru tekniklerle başarılı fide üretimi yapabilirsiniz. Fide çoğaltma, bahçeciliğin en ödüllendirici yönlerinden biridir. Bu rehberde fide çoğaltma teknikleri hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Tohumdan Üretim: Başlangıç Noktası</h3><p>Kaliteli tohumlar seçin. Tohum yatağı hazırlayın ve uygun sıcaklıkta çimlendirin. Tohumlar için özel karışım (torf, perlit, vermikülit) kullanın. Çimlenme için toprak sıcaklığı bitki türüne göre değişir - genellikle 18-25°C idealdir. Tohumları çok derine ekmeYin - genellikle tohum büyüklüğünün 2-3 katı derinlik yeterlidir. Nemli tutun ama ıslak değil. Çimlenme 7-21 gün sürebilir. Fideler 3-4 yapraklı olduğunda şaşırtın. Şaşırtma sırasında köklere dikkat edin. Her fide için ayrı saksı veya hücre kullanın. Yavaş yavaş güneşe alıştırın - direkt güneşe çıkmadan önce yarı gölgede tutun. Tohumdan üretim en ekonomik yöntemdir ancak zaman alır.</p><h3>Çelik Alma: Hızlı Çoğaltma</h3><p>Sağlıklı bitkilerden çelik alın. Çelik 10-15 cm uzunluğunda, yumuşak veya yarı odunsu olabilir. Alt yaprakları çıkarın ve üstte 2-3 yaprak bırakın. Köklendirme hormonu kullanarak kök oluşumunu hızlandırın. Çelikleri nemli karışım (perlit, torf) içine dikin. Yüksek nem sağlayın - plastik torba veya mini sera kullanın. Köklenme 2-6 hafta sürebilir. Köklenme sonrası yavaş yavaş açık havaya alıştırın. Domates, biber, fesleğen gibi bitkiler çelikle kolayca çoğaltılabilir. Çelik alma, aynı özelliklere sahip bitkiler üretir. Ana bitkiden çelik alırken steril aletler kullanın.</p><h3>Bölme Yöntemi: Kök ve Soğan Bölme</h3><p>Bazı bitkiler kök veya soğan bölerek çoğaltılabilir. Her bölümün kök ve yaprak içermesi gerekir. Bölme işlemi genellikle dinlenme döneminde yapılır. Çilek, nane, maydanoz gibi bitkiler bölünerek çoğaltılabilir. Bölme sırasında köklere zarar vermemeye dikkat edin. Her bölümü ayrı saksıya veya toprağa dikin. Bölme sonrası bolca su verin. Bölme yöntemi ile hızlı çoğaltma yapılabilir. Soğan, sarımsak gibi bitkiler dişlerine ayrılarak çoğaltılır. Bölme yöntemi genetik olarak aynı bitkiler üretir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?q=80&w=2070'
WHERE slug = 'fide-cogaltma-teknikleri-tohumdan-ve-celikten-uretim';

-- 23. DİKEY BAHÇE TEKNİĞİ
UPDATE blogs SET
  excerpt = 'Dikey bahçe nasıl yapılır? Küçük balkonlarda ve alanlarda dikey bahçe teknikleri ile daha fazla ürün yetiştirme rehberi. Kurulum, bitki seçimi, bakım ve avantajlar.',
  content = '<h2>Dikey Bahçe Tekniği: Alan Tasarrufu ve Verimlilik</h2><p>Dikey bahçe, sınırlı alanlarda maksimum verim almanın en etkili yöntemidir. Özellikle şehir hayatında ve küçük balkonlarda ideal bir çözümdür. Dikey bahçe teknikleri hem alan tasarrufu sağlar hem de dekoratif bir görünüm sunar. Bu rehberde dikey bahçe kurulumu ve bakımı hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Kurulum: Sistem Seçimi</h3><p>Duvara monte edilen saksılar, askılı sistemler veya dikey kuleler kullanın. Sağlam destek sistemi kurun. Dikey bahçe sistemleri genellikle PVC boru, ahşap kule veya duvar saksılarından oluşur. Güvenli montaj için duvar tipini kontrol edin. Ağırlık taşıma kapasitesini göz önünde bulundurun. Sistem seçerken büyüme alanı, sulama kolaylığı ve erişilebilirlik faktörlerini değerlendirin. Dikey sistemler modüler olabilir ve ihtiyaca göre genişletilebilir. Kurulum öncesi alan planlaması yapın.</p><h3>Bitki Seçimi: Uygun Türler</h3><p>Küçük köklü bitkiler seçin. Yeşillikler, çilek ve küçük sebzeler idealdir. Marul, roka, maydanoz, çilek, çeri domates, biber gibi bitkiler dikey bahçe için mükemmeldir. Büyük köklü bitkiler (domates, patlıcan) dikey sistemler için uygun değildir. Bitki büyüklüğünü ve ağırlığını dikkate alın. Asıcı veya tırmanıcı bitkiler dikey bahçe için idealdir. Bitki seçerken güneş ihtiyacını da göz önünde bulundurun. Dikey sistemlerde üstteki bitkiler daha fazla güneş alır.</p><h3>Bakım: Özel Dikkat Gerekenler</h3><p>Üstten aşağıya sulama yapın. Üst seviyelerden başlayarak sulama yapın, su aşağı doğru akacaktır. Dikey sistemlerde su kaybı daha fazla olabilir. Gübreleme için suda çözünen gübreler kullanın. Düzenli budama yapın - bitkiler büyüdükçe alan sınırlı kalabilir. Dikey bahçelerde hava sirkülasyonu iyi olmalıdır. Bitkileri düzenli olarak kontrol edin - erişilemeyen yerler sorun çıkarabilir. Sulama sistemi kurmak bakımı kolaylaştırır. Dikey sistemlerde drenaj çok önemlidir - fazla suyun tahliyesi gerekir.</p><h3>Avantajlar: Neden Dikey Bahçe?</h3><p>Az yer kaplar - küçük alanlarda maksimum üretim. Daha fazla ürün alırsınız - metrekare başına daha fazla bitki. Dekoratif görünür - ev ve bahçe estetiğini artırır. Bakımı kolaydır - erişilebilir yükseklikte. Güneş kullanımı verimlidir - bitkiler güneş ışığından maksimum faydalanır. Hastalık riski düşüktür - iyi havalandırma sağlar. Dikey bahçe özellikle şehir bahçeciliği için idealdir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2070'
WHERE slug = 'dikey-bahce-teknigi-kucuk-alanlarda-maksimum-verim';

-- 24. KOMPOST YAPIMI
UPDATE blogs SET
  excerpt = 'Evde kompost nasıl yapılır? Organik atıklardan kompost üretimi, kompost çeşitleri, malzeme seçimi, süreç yönetimi ve kullanım yöntemleri hakkında detaylı rehber.',
  content = '<h2>Kompost Yapımı: Doğal Gübre Üretimi</h2><p>Kompost, evsel atıklardan üretilen en değerli organik gübredir. Hem çevreye katkı sağlar hem de bahçenize besin verir. Kompost yapımı, organik atıkların değerli bir kaynağa dönüşmesini sağlar. Bu rehberde kompost yapımı hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Kompost Çeşitleri: Hangi Yöntemi Seçmeli?</h3><p><strong>Soğuk kompost:</strong> Yavaş ama kolay yöntem. Organik atıkları yığın haline getirin ve doğal ayrışmayı bekleyin. 6-12 ay içinde hazır olur. Sürekli bakım gerektirmez. Basit ve uygulaması kolaydır.</p><p><strong>Sıcak kompost:</strong> Hızlı ama daha fazla çaba gerektirir. Doğru karbon-azot oranı ile hızlı ayrışma sağlanır. 3-6 ay içinde hazır olur. Düzenli karıştırma ve nem kontrolü gerekir. Sıcaklık 60-70°C''ye çıkar ve zararlı organizmaları öldürür.</p><p><strong>Solucan kompostu:</strong> En zengin kompost türü. Solucanlar organik atıkları sindirerek çok değerli bir gübre üretir. Daha az alan gerektirir. İç mekanda da yapılabilir. Solucan kompostu (vermikompost) bitkiler için çok besleyicidir.</p><h3>Malzemeler: Doğru Karışım</h3><p>Yeşil malzeme (sebze artıkları, ot, meyve kabukları) ve kahverengi malzeme (kuru yaprak, karton, dal) karışımı kullanın. İdeal oran: 2 ölçü kahverengi, 1 ölçü yeşil. Yeşil malzeme azot sağlar, kahverengi malzeme karbon sağlar. Et, süt ürünleri, yağlı yiyecekler ve hastalıklı bitkiler komposta eklenmemelidir. Karbon-azot dengesi kompost kalitesini belirler. Parçalama hızlandırır - küçük parçalar daha hızlı ayrışır.</p><h3>Süreç: Ayrışma Yönetimi</h3><p>Katmanlar halinde yerleştirin, düzenli karıştırın ve nemli tutun. Kompost nemli ama ıslak olmamalıdır. Karıştırma hava akışı sağlar ve ayrışmayı hızlandırır. Haftada bir kez karıştırma yeterlidir. Sıcak kompost için sıcaklığı izleyin. Kompost hazır olduğunda toprak gibi kokar ve koyu kahverengi renk alır. Ayrışma süresi malzeme tipine, hava sıcaklığına ve karıştırma sıklığına bağlıdır. Kompost hazır olduğunda orijinal malzemeler tanınmaz hale gelir.</p><h3>Kullanım: Değerli Gübre</h3><p>Hazır kompostu toprağa karıştırın veya üst malç olarak kullanın. Fideler için mükemmel bir besin kaynağıdır. Kompost toprak yapısını iyileştirir ve su tutma kapasitesini artırır. Dikim öncesi toprağa %20-30 kompost ekleyin. Kompost doğal bir gübre olduğu için aşırı kullanım riski düşüktür. Kompost, bitkilerin ihtiyaç duyduğu tüm besin maddelerini sağlar. Toprak mikroorganizmalarını destekler ve toprak sağlığını artırır. Kompost sıvı olarak da kullanılabilir - kompost çayı yapılabilir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?q=80&w=2070'
WHERE slug = 'kompost-yapimi-evde-organik-gubre-uretime';

-- 25. BAHÇE PLANLAMA
UPDATE blogs SET
  excerpt = 'Bahçe planlaması nasıl yapılır? Fide düzeni, rotasyon sistemi, alan değerlendirmesi, yol planlaması ve verimli bahçe tasarımı hakkında profesyonel ipuçları ve detaylı rehber.',
  content = '<h2>Bahçe Planlama: Verimli ve Organize Bahçe</h2><p>İyi planlanmış bir bahçe, hem görsel olarak güzel hem de verimli olur. Doğru düzenleme ile maksimum ürün alırsınız. Bahçe planlaması, başarılı bahçeciliğin temelidir. Bu rehberde bahçe planlama konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Alan Değerlendirmesi: Başlangıç Analizi</h3><p>Güneş alan yerleri belirleyin. Günde en az 6 saat güneş alan alanlar idealdir. Güneş yönüne göre bitki yerleşimini planlayın. Su kaynağına yakınlığı kontrol edin. Sulama için pratik erişim önemlidir. Toprak kalitesini analiz edin. pH, besin durumu ve drenaj özelliklerini test edin. Alan büyüklüğünü ve şeklini değerlendirin. Rüzgar durumunu göz önünde bulundurun - rüzgar koruması gerekebilir. Erişim yollarını planlayın. Güneş gölge haritası çıkarın - hangi alanlar ne kadar güneş alıyor belirleyin.</p><h3>Fide Düzeni: Optimal Yerleşim</h3><p>Yüksek bitkileri kuzeye, alçak bitkileri güneye dikin. Böylece tüm bitkiler güneşten faydalanır. Birlikte uyumlu bitkileri yan yana yerleştirin. Companion planting tekniklerini kullanın. Bitki boylarına göre güneş gölge planlaması yapın. Mesafeleri doğru ayarlayın - her bitki için yeterli alan önemlidir. Sıra düzeni veya karışık dikim yapılabilir. Sıra düzeni büyük bahçeler için idealdir. Karışık dikim küçük bahçeler ve organik bahçecilik için uygundur. Bitki familyalarını gruplandırın - aynı bakım gereksinimlerine sahip bitkileri birlikte dikin.</p><h3>Rotasyon: Toprak Sağlığı İçin</h3><p>Her yıl bitki yerlerini değiştirin. Rotasyon hastalık ve zararlı riskini azaltır. Aynı familyadan bitkileri aynı yere 3 yıl üst üste dikmeyin. Rotasyon planı 3-4 yıllık döngü olmalıdır. Örneğin: Yıl 1 - Domates, Yıl 2 - Lahana, Yıl 3 - Fasulye, Yıl 4 - Soğan. Rotasyon toprak besin dengesini korur. Her bitki farklı besinler tüketir ve farklı kök derinliğine sahiptir. Rotasyon kayıtlarını tutun - hangi bitki nereye dikildi not edin. Rotasyon planı bahçe planının bir parçası olmalıdır.</p><h3>Yollar ve Erişim: Pratik Düzen</h3><p>Hasat ve bakım için yeterli yol alanı bırakın. Ana yollar en az 60 cm genişliğinde olmalıdır. Yan yollar 30-40 cm yeterlidir. Saksılar arasında geçiş yolları oluşturun. Yolların drenajı iyi olmalıdır - çamurlu yollar sorun çıkarır. Yolları malç veya taşla kaplayın. Erişilebilirlik önemlidir - her bitkiye kolayca erişilebilmelidir. Yol planlaması bahçe büyüklüğüne göre değişir. Küçük bahçelerde yol ihtiyacı azdır. Büyük bahçelerde yollar mutlaka planlanmalıdır. Yol planlaması bahçe verimliliğini artırır.</p>',
  featured_image = 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=2070'
WHERE slug = 'bahce-planlama-fide-duzeni-ve-rotasyon-sistemi';

-- PARÇA 5 TAMAMLANDI (Blog 21-25)

