-- ============================================
-- BLOG GÜNCELLEMELERİ - PARÇA 6/6
-- Blog 26-30: Detaylı içerikler ve konuya uygun resimler
-- ============================================
-- Bu SQL dosyasını Supabase Dashboard > SQL Editor'de çalıştırın

-- 26. BİRLİKTE UYUMLU BİTKİLER (COMPANION PLANTING)
UPDATE blogs SET
  excerpt = 'Hangi bitkiler birlikte dikilir? Companion planting nedir? Zararlı böcekleri uzaklaştıran, verimi artıran ve birbirine fayda sağlayan bitki kombinasyonları hakkında detaylı rehber.',
  content = '<h2>Birlikte Uyumlu Bitkiler: Companion Planting Rehberi</h2><p>Bazı bitkiler birlikte dikildiğinde birbirlerine fayda sağlar. Bu teknik hem verimi artırır hem de zararlıları uzaklaştırır. Companion planting, organik bahçeciliğin önemli tekniklerinden biridir. Bu rehberde birlikte uyumlu bitkiler hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Klasik Kombinasyonlar: Kanıtlanmış Eşleşmeler</h3><p><strong>Domates + Fesleğen:</strong> Fesleğen zararlıları uzaklaştırır ve domatesin lezzetini artırır. Fesleğen yaprak bitlerini ve örümcek akarlarını uzaklaştırır. Bu kombinasyon hem lezzet hem de sağlık açısından idealdir.</p><p><strong>Havuç + Soğan:</strong> Soğan havuç sineğini uzaklaştırır. Havuç kokusu soğan sineğini de uzaklaştırır. Bu karşılıklı koruma sistemi her iki bitki için de faydalıdır.</p><p><strong>Salatalık + Dereotu:</strong> Dereotu salatalığa iyi gelir ve zararlıları uzaklaştırır. Dereotu yararlı böcekleri çeker ve salatalık verimini artırır. Bu kombinasyon özellikle balkon bahçeciliği için idealdir.</p><p><strong>Fasulye + Mısır:</strong> Mısır fasulyeye destek sağlar, fasulye ise toprağa azot bağlar. Bu karşılıklı fayda ilişkisi klasik bir örnektir. Her iki bitki de birbirinden faydalanır.</p><h3>Çiçekler ve Yararlı Böcekler</h3><p>Kadife çiçeği, lavanta ve kekik gibi bitkiler zararlı böcekleri uzaklaştırır ve arıları çeker. Kadife çiçeği kök nematodlarını uzaklaştırır ve yaprak bitlerini caydırır. Lavanta güçlü kokusuyla zararlıları uzaklaştırır ve yararlı böcekleri çeker. Kekik geniş spektrumlu bir koruma sağlar. Çiçekler ayrıca bahçeye güzellik katar. Nasturtium (kaynata dili) yaprak bitlerini çeker ve ana bitkileri korur. Calendula (ay çiçeği) yararlı böcekleri çeker. Bu çiçekler bahçe kenarlarına veya bitkiler arasına dikilebilir.</p><h3>Kaçınılması Gereken Kombinasyonlar</h3><p>Domates ve patates aynı yerde yetişmemeli - aynı hastalıklara yakalanırlar ve rekabet ederler. Biber ve fasulye de birbirine çok yakın olmamalıdır - benzer besin ihtiyacı nedeniyle rekabet ederler. Soğan ve bezelye birlikte dikilmemelidir - bezelye soğanın büyümesini engeller. Bazı bitkiler birbirinin büyümesini engelleyen kimyasallar salgılar. Bu durumlar companion planting''in tersi olan allelopati olarak bilinir. Bitki kombinasyonlarını seçerken bu faktörleri göz önünde bulundurun.</p><h3>Uygulama İpuçları</h3><p>Companion planting için bitkileri yakın ama birbirine çok sıkışık dikmeyin. Yeterli alan her bitkinin sağlıklı büyümesi için gereklidir. Dönüşümlü dikim yaparak farklı kombinasyonları deneyin. Hangi kombinasyonlar bahçenizde en iyi sonucu veriyor not edin. Companion planting kayıtları tutun - hangi bitkiler iyi birlikte büyüyor belirleyin. Büyük bahçelerde farklı bölgelerde farklı kombinasyonlar deneyebilirsiniz. Küçük bahçelerde ise en etkili kombinasyonları seçin. Companion planting zaman içinde bahçenizde doğal bir denge kurar.</p>',
  featured_image = 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2070'
WHERE slug = 'birlikte-uyumlu-bitkiler-companion-planting-rehberi';

-- 27. SEBZE HASADI
UPDATE blogs SET
  excerpt = 'Sebzeler ne zaman hasat edilir? Hasat zamanı belirleme, hasat yöntemleri, taze sebze saklama teknikleri ve hasat sonrası bakım hakkında detaylı rehber.',
  content = '<h2>Sebze Hasadı: Doğru Zaman ve Yöntem</h2><p>Doğru zamanda hasat, lezzet ve besin değeri açısından kritik öneme sahiptir. Her sebze için optimal hasat zamanı farklıdır. Hasat teknikleri ürün kalitesini doğrudan etkiler. Bu rehberde sebze hasadı konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Hasat Zamanı: Bitki Türüne Göre</h3><p><strong>Domates:</strong> Tam kırmızı ama sertken hasat edin. Tam olgunlaşmadan topladıklarınızı güneşte olgunlaştırabilirsiniz. Hasat zamanı çeşide göre değişir - erkenci çeşitler 60-70 günde, geç çeşitler 80-100 günde hasat edilir. Domates sapından hafifçe çevirerek koparılır.</p><p><strong>Biber:</strong> İstediğiniz boyutta hasat edilebilir. Yeşil biberler erken hasat edilir, renkli çeşitler tam renklenince hasat edilir. Düzenli hasat yeni meyve oluşumunu teşvik eder. Biber sapından makasla kesilerek hasat edilir.</p><p><strong>Salatalık:</strong> Küçük ve gevrekken hasat edin - genellikle 15-20 cm boyunda. Büyük salatalıklar çekirdekli ve acı olur. Düzenli hasat sürekli üretim sağlar. Sabah erken saatlerde hasat yapmak meyvelerin daha gevrek olmasını sağlar.</p><p><strong>Yeşillikler:</strong> Yapraklar tam gelişmişken hasat edin. Dıştan içe doğru hasat yaparak bitkinin büyümeye devam etmesini sağlayın. Hasat sonrası yapraklar hemen tüketilmeli veya buzdolabında saklanmalıdır. Yeşillikler hızlı bozulur.</p><h3>Hasat Yöntemi: Doğru Teknik</h3><p>Makas veya bıçak kullanın - temiz ve keskin aletler kullanın. Çekerek koparmayın - bu bitkiye zarar verir. Hasat sırasında bitkiye zarar vermeyin. Hasat sırasında dikkatli olun - bitkiler hassastır. Hasat sırasında bitkilerin diğer kısımlarına dokunmamaya çalışın. Hasat sonrası aletleri temizleyin. Hastalık bulaşmasını önlemek için temiz aletler kullanın. Hasat sırasında yapraklara ve gövdelerine zarar vermeyin. Doğru hasat teknikleri bitki sağlığını korur.</p><h3>Saklama: Tazelik Koruma</h3><p>Taze sebzeleri serin ve nemli yerde saklayın. Buzdolabında saklarken nemli bez kullanın. Hasattan hemen sonra tüketmek en iyisidir. Sebzelerin çoğu buzdolabında 3-7 gün saklanabilir. Domates buzdolabına konmamalı - oda sıcaklığında saklanmalıdır. Sebzeleri yıkamadan saklayın - yıkama bozulmayı hızlandırır. Sebzeleri ayrı ayrı saklayın - bazı sebzeler erilen gaz salgılar ve diğerlerini bozar. Hasat sonrası sebzeleri güneşten koruyun. Dondurma ve konserve yaparak uzun süre saklayabilirsiniz.</p>',
  featured_image = 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=2070'
WHERE slug = 'sebze-hasadi-en-iyi-hasat-zamani-ve-yontemleri';

-- 28. HİDROPONİK FİDE YETİŞTİRME
UPDATE blogs SET
  excerpt = 'Hidroponik sistem nasıl kurulur? Topraksız tarım, hidroponik fide yetiştirme, sistem kurulumu, besin çözeltisi ve evde hidroponik sistem hakkında detaylı rehber.',
  content = '<h2>Hidroponik Yetiştirme: Modern Tarım Yöntemi</h2><p>Hidroponik, toprak olmadan bitki yetiştirme yöntemidir. Su içinde çözünmüş besinlerle bitkiler yetiştirilir. Hidroponik sistemler, kontrollü ortamlarda yüksek verim sağlar. Bu rehberde hidroponik fide yetiştirme konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Sistem Kurulumu: Temel Sistemler</h3><p><strong>Basit sistem:</strong> Su tankı, pompa ve büyüme yatağı. Basit sistemler ev bahçeciliği için idealdir. NFT (Nutrient Film Technique) sistemi: Sürekli akan su ile besin taşınır. DWC (Deep Water Culture) sistemi: Derin su kültürü, kökler su içinde gelişir. Ebb and Flow sistemi: Su periyodik olarak yükselip alçalır. Sistem seçimi büyüklük, bütçe ve deneyim seviyesine bağlıdır. Basit sistemlerle başlayın ve deneyim kazandıkça geliştirin.</p><h3>Besin Çözeltisi: Kritik Faktör</h3><p>Hidroponik besin solüsyonu kullanın. pH seviyesini 5.5-6.5 arasında tutun. EC (elektriksel iletkenlik) değerini düzenli kontrol edin. Besin çözeltisini haftada bir değiştirin veya yenileyin. Besin konsantrasyonu bitki gelişim dönemine göre ayarlanmalıdır. Genç bitkiler için daha seyreltilmiş çözelti kullanın. pH ve EC ölçümleri için özel cihazlar gereklidir. Besin eksiklikleri yaprak renklerinden anlaşılabilir. Hidroponik besin çözeltileri özel formüle edilmiştir ve bitkilerin tüm ihtiyaçlarını karşılar.</p><h3>Avantajlar: Neden Hidroponik?</h3><p>Daha hızlı büyüme - bitkiler enerjiyi kök gelişimine değil yaprak ve meyve üretimine harcar. Daha yüksek verim - kontrollü ortamda maksimum üretim sağlanır. Az su kullanımı - su döngüsü ile %90 su tasarrufu. Hastalık riski düşük - toprak kaynaklı hastalıklar yok. Yıl boyunca üretim - kontrollü ortamda mevsimsiz üretim. Küçük alanlarda büyük üretim - dikey sistemler ile alan tasarrufu. Hidroponik sistemler özellikle şehir bahçeciliği için idealdir.</p><h3>Başlangıç: İlk Adımlar</h3><p>Basit sistemlerle başlayın. Yeşillikler ve marul hidroponik için idealdir - hızlı büyür ve kolay yetiştirilir. Domates, biber gibi bitkiler daha gelişmiş sistemler gerektirir. Deneyim kazandıkça sisteminizi genişletin. Hidroponik sistemler için yeterli ışık gereklidir - doğal ışık veya LED bitki ışıkları kullanılabilir. Sistem bakımı düzenli olmalıdır - pompa, besin çözeltisi ve pH kontrolü önemlidir. Hidroponik sistemler başlangıçta yatırım gerektirir ancak uzun vadede verimli olur.</p>',
  featured_image = 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?q=80&w=2070'
WHERE slug = 'hidroponik-fide-yetistirme-topraksiz-tarim-rehberi';

-- 29. ORGANİK BAHÇE SERTİFİKASYONU
UPDATE blogs SET
  excerpt = 'Organik bahçe nasıl sertifikalanır? Organik üretim standartları, sertifikasyon süreci, dönüşüm periyodu, kayıt ve denetim hakkında detaylı bilgiler.',
  content = '<h2>Organik Bahçe Sertifikasyonu: Kalite ve Güven</h2><p>Organik sertifikasyon, ürünlerinizin organik standartlara uygun olduğunu gösterir. Sertifikasyon süreci, ürünlerinizin sağlıklı ve çevre dostu olduğunu garanti eder. Bu rehberde organik bahçe sertifikasyonu hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Organik Üretim Standartları</h3><p>Organik tohum ve fide kullanımı - sentetik işlem görmemiş tohumlar kullanılmalıdır. Sentetik gübre ve ilaç yasağı - sadece organik gübre ve doğal mücadele yöntemleri kullanılabilir. Doğal gübre ve mücadele yöntemleri - kompost, solucan gübresi, organik ilaçlar kullanılmalıdır. Toprak sağlığı korunmalı - toprak yapısı ve mikroorganizma dengesi korunmalıdır. GMO (genetiği değiştirilmiş organizma) yasağı - GMO içeren ürünler kullanılamaz. Organik standartlar ulusal ve uluslararası düzenlemelerle belirlenir. Standartlara uyum denetimlerle kontrol edilir.</p><h3>Sertifikasyon Süreci: Adım Adım</h3><p>Organik dönüşüm süreci en az 2 yıl sürer. Bu süreçte organik yöntemler kullanılır ancak ürünler henüz sertifikalı değildir. Dönüşüm sürecinde toprak analizi yapılır. Organik sertifikasyon kuruluşuna başvuru yapılır. Başvuru sonrası inceleme ve denetimler yapılır. Başarılı denetim sonrası sertifika verilir. Sertifikasyon süreci düzenli denetimlerle devam eder. Kayıt tutulur ve raporlama yapılır. Sertifika süresi genellikle 1 yıldır ve yenilenir. Sertifikasyon sürecinde tüm uygulamalar kayıt altına alınır.</p><h3>Kayıt ve Denetim: Süreklilik</h3><p>Sertifikasyon kuruluşuna düzenli raporlama yapılır. Yılda en az bir kez denetim yapılır. Denetimlerde toprak, ürün ve uygulamalar kontrol edilir. Uyumsuzluk durumunda sertifika iptal edilebilir. Kayıtlar düzenli tutulmalıdır - dikim, gübreleme, ilaçlama kayıtları tutulur. Denetim öncesi hazırlık yapılmalıdır. Tüm belgeler hazır olmalıdır. Sertifikasyon süreci şeffaf olmalıdır. Denetim sonuçları raporlanır ve gerekirse düzeltmeler yapılır.</p><h3>Avantajlar: Değer ve Güven</h3><p>Sağlıklı ürünler - organik ürünler kimyasal kalıntı içermez. Çevre koruma - doğal kaynaklar korunur ve sürdürülebilir tarım yapılır. Yüksek değer - organik ürünler daha değerlidir ve daha iyi fiyat alır. Güven tesis eder - tüketiciler organik sertifikaya güvenir. Pazar avantajı - organik ürünler için özel pazarlar vardır. Uzun vadeli toprak sağlığı - organik yöntemler toprağı iyileştirir. Organik sertifikasyon, bahçenizin kalitesini ve değerini artırır.</p>',
  featured_image = 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=2070'
WHERE slug = 'organik-bahce-sertifikasyonu-organik-uretim-standartlari';

-- 30. BAHÇE GÜNLÜĞÜ TUTMA
UPDATE blogs SET
  excerpt = 'Bahçe günlüğü nasıl tutulur? Fide dikimi, bakım notları, hasat kayıtları, hava durumu, hastalık kayıtları ve bahçe planlaması için günlük tutma rehberi.',
  content = '<h2>Bahçe Günlüğü Tutma: Başarılı Bahçıvanın Sırrı</h2><p>Bahçe günlüğü, başarılı bahçıvanların en önemli araçlarından biridir. Gelecek sezonlar için değerli bilgiler sağlar. Düzenli kayıt tutmak, bahçecilik deneyiminizi zenginleştirir ve hatalardan öğrenmenizi sağlar. Bu rehberde bahçe günlüğü tutma konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Neler Kaydedilmeli: Önemli Bilgiler</h3><p><strong>Dikim tarihleri ve yerleri:</strong> Hangi bitki ne zaman ve nereye dikildi. Dikim tarihleri gelecek sezonlar için referanstır. Bitki yerleri rotasyon planlaması için önemlidir.</p><p><strong>Çeşit isimleri ve kaynakları:</strong> Hangi çeşitler kullanıldı ve nereden alındı. Çeşit performansı gelecek sezonlar için rehberdir. İyi sonuç veren çeşitler not edilmelidir.</p><p><strong>Hava durumu ve sıcaklık:</strong> Günlük hava durumu, sıcaklık ve yağış kayıtları. Hava durumu bitki gelişimini etkiler. İklim verileri gelecek sezonlar için faydalıdır.</p><p><strong>Sulama ve gübreleme programı:</strong> Ne zaman ve ne kadar sulama/gübreleme yapıldı. Uygulama kayıtları optimal programı belirlemeye yardımcı olur. Aşırı veya yetersiz uygulamalar not edilmelidir.</p><p><strong>Hastalık ve zararlı kayıtları:</strong> Hangi hastalık/zararlı ne zaman görüldü ve nasıl mücadele edildi. Mücadele yöntemlerinin etkinliği not edilmelidir. Önleyici tedbirler için referanstır.</p><p><strong>Hasat tarihleri ve miktarları:</strong> Ne zaman hasat yapıldı ve ne kadar ürün alındı. Verim kayıtları çeşit karşılaştırması için önemlidir. Hasat zamanları gelecek sezonlar için rehberdir.</p><h3>Faydaları: Gelecek İçin Rehber</h3><p>Hangi çeşitler iyi yetişti - performans karşılaştırması yapabilirsiniz. Ne zaman dikim yapılmalı - optimal dikim zamanlarını belirlersiniz. Hangi sorunlarla karşılaştık - hatalardan öğrenirsiniz. Gelecek sezon için planlama yapılır - deneyimler planlamaya yön verir. Başarı faktörlerini belirlersiniz - neyin işe yaradığını görürsünüz. Sorunları çözmek için veri toplarsınız - sistematik yaklaşım sağlar. Bahçe günlüğü zaman içinde değerli bir referans kaynağı haline gelir.</p><h3>Yöntem: Kayıt Tutma Araçları</h3><p>Not defteri - geleneksel ve basit yöntem. Dijital uygulama - fotoğraf, grafik ve arama özellikleri. Fotoğraf günlüğü - görsel kayıt tutma. Spreadsheet (Excel) - veri analizi için uygun. Mobil uygulamalar - her yerde erişilebilir. Hangi yöntem seçilirse seçilsin, düzenli kayıt tutmak önemlidir. Haftalık veya günlük güncelleme yapın. Kayıtları düzenli tutun - düzensiz kayıtlar değersizdir. Bahçe günlüğü tutma bir alışkanlık haline gelmelidir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2070'
WHERE slug = 'bahce-gunlugu-tutma-basarili-bahcivanin-sirri';

-- 31. ÇOCUKLARLA BAHÇE (BONUS - 30. BLOG)
UPDATE blogs SET
  excerpt = 'Çocuklarla bahçe nasıl yapılır? Aile bahçeciliği, çocuklar için bahçe etkinlikleri, eğitici bahçe projeleri, güvenlik önlemleri ve aile aktiviteleri hakkında detaylı rehber.',
  content = '<h2>Çocuklarla Bahçe: Eğitici ve Eğlenceli Aktivite</h2><p>Bahçecilik, çocuklar için hem eğitici hem de eğlenceli bir aktivitedir. Doğayı tanımalarına ve sorumluluk almalarına yardımcı olur. Çocuklarla bahçe yapmak, aile bağlarını güçlendirir ve kalıcı anılar oluşturur. Bu rehberde çocuklarla bahçe konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Başlangıç Projeleri: Çocuk Dostu Seçenekler</h3><p><strong>Hızlı büyüyen bitkiler:</strong> Turp, marul, fasulye gibi hızlı sonuç veren bitkiler. Çocuklar sabırsızdır, hızlı sonuçlar ilgilerini korur. Turp 3-4 haftada hasat edilir. Fasulye 6-8 haftada meyve verir.</p><p><strong>Renkli sebzeler:</strong> Turuncu havuç, mor lahana, kırmızı domates gibi renkli çeşitler. Renkli sebzeler çocukların ilgisini çeker. Renk çeşitliliği görsel çekiciliği artırır.</p><p><strong>Çocukların sevdiği sebzeler:</strong> Domates, çilek, bezelye gibi lezzetli ve kolay yenen sebzeler. Kendi yetiştirdikleri sebzeleri yemek çocuklar için ödüllendiricidir. Lezzetli sebzeler çocukların sebze sevgisini artırır.</p><h3>Eğitici Değer: Hayat Dersleri</h3><p>Bitki yaşam döngüsü - tohumdan meyveye kadar süreç çocuklara öğretilir. Sorumluluk - düzenli bakım çocuklara sorumluluk duygusu verir. Sabır - bitki büyümesi zaman alır, sabır öğretir. Doğa sevgisi - doğayla iç içe olmak çocuklarda doğa sevgisi oluşturur. Bilimsel düşünce - gözlem ve deney yapma fırsatı sağlar. Beslenme bilgisi - sebzelerin besin değeri öğretilir. Çevre bilinci - doğayı koruma ve sürdürülebilirlik kavramları öğretilir. Bahçecilik, çocukların çok yönlü gelişimine katkı sağlar.</p><h3>Güvenlik: Öncelik</h3><p>Güvenli aletler kullanın - çocuklar için uygun boyutta ve güvenli aletler. Organik yöntemler tercih edin - kimyasallardan kaçının. Sürekli gözetim sağlayın - çocuklar yalnız bırakılmamalıdır. Güvenli bitkiler seçin - zehirli bitkilerden kaçının. Alet kullanımında rehberlik yapın - doğru kullanım öğretilmelidir. Güneş koruması - şapka ve güneş kremi kullanın. Su güvenliği - su birikintileri ve açık sular tehlikelidir. Güvenlik her zaman öncelikli olmalıdır.</p><h3>Aile Aktiviteleri: Birlikte Zaman</h3><p>Birlikte dikim yapın - ailece bahçe zamanı geçirin. Sulama sırası belirleyin - herkese görev verin. Hasat kutlaması yapın - başarıları kutlayın. Yemek pişirme - yetiştirdiğiniz sebzelerle yemek yapın. Fotoğraf çekme - anıları kaydedin. Bahçe gezileri - başka bahçeleri ziyaret edin. Bahçe yarışmaları - en güzel sebze yarışması yapın. Aile bahçeciliği, kaliteli zaman geçirmenin en güzel yollarından biridir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?q=80&w=2070'
WHERE slug = 'cocuklarla-bahce-aile-bahceciligi-ve-egitici-etkinlikler';

-- PARÇA 6 TAMAMLANDI (Blog 26-30)
-- TÜM 30 BLOG GÜNCELLENDİ! ✅

