-- ============================================
-- BLOG GÜNCELLEMELERİ - PARÇA 4/6
-- Blog 16-20: Detaylı içerikler ve konuya uygun resimler
-- ============================================
-- Bu SQL dosyasını Supabase Dashboard > SQL Editor'de çalıştırın

-- 16. ÇİLEK FİDESİ DİKİMİ VE BAKIMI
UPDATE blogs SET
  excerpt = 'Çilek fidesi nasıl dikilir? Balkonda ve bahçede çilek yetiştirme rehberi. Sulama, gübreleme, kış bakımı ve verimli hasat için ipuçları. Çilek yetiştirme teknikleri.',
  content = '<h2>Çilek Yetiştirme: Bahçenin Tatlı Lezzeti</h2><p>Çilek, meyve fideleri arasında en popüler olanlarından biridir. Küçük alanlarda bile yetiştirilebilir ve çok yönlü kullanımı vardır. Taze çileklerin tadı hiçbir şeyle karşılaştırılamaz. Bu rehberde çilek yetiştirme konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Fide Dikimi: Doğru Teknik</h3><p>Çilek fidelerini toprağa tam gömmeyin. Kök boğazı toprak üzerinde kalmalıdır. Kök boğazının toprağa gömülmesi bitki çürümesine neden olur. Fideler arası 30 cm mesafe bırakın. Çilek bitkileri yayılıcı bir yapıya sahiptir. Her fide için yeterli alan önemlidir. Dikim sırasında kökleri dikkatli yayın. Kökler bükülmemeli veya zarar görmemelidir. Dikim sonrası bolca su verin. İlk hafta boyunca düzenli sulama yapın. Çilek fidelerini dikerken yaprak taç kısmının toprak yüzeyinde olmasına dikkat edin.</p><h3>Toprak ve Güneş Gereksinimleri</h3><p>İyi drenajlı, humuslu toprak tercih edin. Çilek asidik toprak sever, pH 5.5-6.5 arası idealdir. Günde 6-8 saat güneş ışığı alan yerler idealdir. Toprak yüzeyine malç (saman, talaş veya kuru yapraklar) sererek meyvelerin toprağa değmesini önleyin. Malç ayrıca yabani otları kontrol eder ve toprak nemini korur. Toprak yapısını iyileştirmek için kompost ekleyin. Çilek kökleri sığ gelişir, bu nedenle üst toprak katmanının kaliteli olması önemlidir.</p><h3>Bakım ve Gübreleme</h3><p>Düzenli sulama yapın. Çilek yaprakları nemli havayı sever. Yabani otları temizleyin - otlar çileklerle rekabet eder. Çiçek açtıktan sonra organik gübre verin. Potasyum açısından zengin gübreler meyve kalitesini artırır. Azotlu gübreleri dengeli kullanın. Çilek bitkileri yaprak gelişimi için azota ihtiyaç duyar ancak aşırı azot meyve kalitesini düşürebilir. Çiçeklenme döneminde potasyum ağırlıklı gübre kullanın. Çilek yaprakları sararmaya başlarsa magnezyum eksikliği olabilir.</p><h3>Kış Bakımı: Soğuktan Koruma</h3><p>Kış aylarında bitkileri saman veya yaprakla örtün. Örtü don tehlikesine karşı koruma sağlar. İlkbaharda örtüyü kaldırın ve gübreleyin. Kış aylarında çilek bitkileri dinlenme dönemine girer. Örtü kaldırıldıktan sonra yaprakları temizleyin ve ölü yaprakları çıkarın. Kış sonrası bitkiler yeni yapraklar çıkarır. Çilek bitkileri soğuğa dayanıklıdır ancak sert donlardan korunmalıdır. Kış bakımı çilek bitkilerinin sağlıklı bir şekilde bahara çıkmasını sağlar.</p><h3>Hasat ve Verimlilik</h3><p>Çilekler tam olgunlaştığında hasat edin. Kırmızı, parlak ve tatlı çilekler idealdir. Hasat sırasında meyveyi sapından tutup koparın. Sabah erken saatlerde hasat yapmak meyvelerin daha taze olmasını sağlar. Düzenli hasat yeni çiçek oluşumunu teşvik eder. Çilekler hızlı bozulur, bu nedenle hasattan hemen sonra tüketin veya buzdolabında saklayın. Çilek bitkileri 3-4 yıl verimli kalabilir. Yaşlı bitkileri yenileyin ve yeni fideler dikin. Çilek sürüncüleri (runner) köklendirerek yeni bitkiler elde edebilirsiniz.</p>',
  featured_image = 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?q=80&w=2070'
WHERE slug = 'cilek-fidesi-dikimi-ve-bakimi-ev-bahcesinde-cilek';

-- 17. İLKBAHAR FİDE DİKİMİ
UPDATE blogs SET
  excerpt = 'İlkbahar fide dikimi rehberi: Hangi fideler ne zaman dikilir? İlkbahar bahçe hazırlığı, toprak işleme, fide seçimi ve ilk bakım hakkında detaylı bilgiler. Başarılı sezon için ipuçları.',
  content = '<h2>İlkbahar Fide Dikimi: Yeni Sezonun Başlangıcı</h2><p>İlkbahar, fide dikimi için en uygun mevsimdir. Doğru zamanlama ve hazırlık ile başarılı bir sezon geçirirsiniz. İlkbahar bahçeciliği, yeni başlangıçlar ve bol hasat demektir. Bu rehberde ilkbahar fide dikimi konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Zamanlama: Kritik Faktör</h3><p>Son don tarihinden sonra fide dikmeye başlayın. Türkiye''de genellikle nisan ayı uygundur. Ancak bölgesel iklim farklılıkları nedeniyle yerel don tarihini kontrol edin. Hava sıcaklığı ve toprak sıcaklığını dikkate alın. Toprak sıcaklığı en az 10-15°C olmalıdır. Erken dikimler don riski taşır. Geç dikimler ise büyüme süresini kısaltır. İlkbahar başında soğuğa dayanıklı bitkiler (lahana, marul, ıspanak) dikilebilir. Sıcak havayı seven bitkiler (domates, biber, patlıcan) için mayıs ayını bekleyin. Yerel iklim koşullarını gözlemleyin ve hava durumunu takip edin.</p><h3>Hazırlık: Toprak İşleme</h3><p>Toprağı sonbaharda işleyin. İlkbaharda gübre ekleyin ve fideler için hazırlayın. Toprak analizi yaptırarak pH ve besin durumunu öğrenin. Toprak yapısını iyileştirmek için kompost veya organik gübre ekleyin. Toprak yüzeyini düzleyin ve taşları temizleyin. Sıcaklığı kontrol edin - toprak sıcaklığı yeterli değilse siyah plastik örtü kullanarak ısıtabilirsiniz. Toprak hazırlığı 2-3 hafta önceden başlamalıdır. Toprak işleme sırasında organik madde ekleyin. Hazır toprak yeterince havalanmış ve gevşek olmalıdır. Fidelerin kök gelişimi için toprak yapısı önemlidir.</p><h3>Fide Seçimi: Kaliteli Başlangıç</h3><p>Sağlıklı, kök sistemi gelişmiş fideler seçin. Yaprakları canlı ve yeşil olmalıdır. Aşılı fideler daha dayanıklı olur. Fide seçerken yapraklarda sararma, lekelenme veya böcek zararı olmamalıdır. Kök sistemi beyaz ve sağlıklı olmalıdır. Fidelerin boyu çok uzun ve ince olmamalıdır. Kompakt ve sağlam fideler tercih edilmelidir. Çeşit seçerken bölgenizin iklim koşullarına uygun olanları seçin. Erkenci çeşitler erken hasat sağlar. Dayanıklı çeşitler hastalık ve zararlılara karşı daha dirençlidir.</p><h3>İlk Bakım: Başarılı Adaptasyon</h3><p>Dikimden sonra bolca su verin. İlk hafta düzenli sulama yapın. Fidelerin kök sistemi gelişene kadar toprak nemli tutulmalıdır. Gübreleme 2-3 hafta sonra başlayın. İlk haftalarda kök gelişimi önceliklidir. Soğuk gecelerde fideleri koruyun - geçici örtüler kullanabilirsiniz. Yabani otları temizleyin. Fideler büyüdükçe destek sistemleri kurun. İlk haftalarda fidelerin adaptasyonu için dikkatli bakım yapın. Yapraklarda solma veya sararma görürseniz nedeni araştırın. Erken müdahale fidelerin sağlıklı büyümesini sağlar.</p>',
  featured_image = 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=2070'
WHERE slug = 'ilkbahar-fide-dikimi-ne-zaman-ve-nasil';

-- 18. YAZ AYLARINDA FİDE BAKIMI
UPDATE blogs SET
  excerpt = 'Yaz sıcaklarında fide bakımı nasıl yapılır? Su ihtiyacı, güneş koruması, sıcaklık yönetimi, malçlama ve hastalık kontrolü hakkında pratik ipuçları. Yaz bahçeciliği rehberi.',
  content = '<h2>Yaz Aylarında Fide Bakımı: Sıcaklık Yönetimi</h2><p>Yaz ayları, fideler için hem büyüme hem de zorluk dönemidir. Doğru bakımla yazı sorunsuz geçirirsiniz. Yaz sıcakları bitkilerin su ihtiyacını artırır ve bazı hastalıklara yol açabilir. Bu rehberde yaz aylarında fide bakımı konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Su Yönetimi: Artan İhtiyaç</h3><p>Yazın su ihtiyacı artar. Sabah erken veya akşamüstü sulama yapın. Öğle sıcağında sulamayın çünkü su buharlaşır ve yapraklar yanabilir. Toprak nemli tutulmalıdır. Sıcak günlerde günde iki kez sulama gerekebilir. Sabah erken sulama (06:00-09:00) idealdir. Akşam sulaması da yapılabilir ancak yaprakların gece nemli kalması mantar hastalıklarına yol açabilir. Damlama sulama sistemi yaz aylarında çok etkilidir. Toprak nemini düzenli olarak kontrol edin. Yapraklarda solma görürseniz derhal sulayın. Su kalitesi önemlidir - tuzlu sudan kaçının.</p><h3>Gölgeleme: Güneş Koruması</h3><p>Aşırı güneşten bitkileri koruyun. Gölgelik kullanın veya yüksek bitkiler dikin. Özellikle öğle saatlerinde (11:00-15:00) gölgeleme önemlidir. Yapraklarda yanma görürseniz önlem alın. Yanmış yapraklar kahverengi veya sarı olur. Gölgelik %30-50 gölge sağlayabilir. Yüksek bitkiler (mısır, ayçiçeği) küçük bitkilere gölge yapar. Serin iklim bitkileri yaz sıcaklarında özellikle korunmalıdır. Gölgeleme aşırı sıcaklıktan korur ve su kaybını azaltır. Saksı bitkilerini sıcak öğle saatlerinde gölgeye taşıyabilirsiniz.</p><h3>Malçlama: Su ve Sıcaklık Kontrolü</h3><p>Toprak yüzeyine malç serin. Bu hem su kaybını önler hem de toprak sıcaklığını düşürür. Organik malç (saman, kuru yaprak, talaş) kullanabilirsiniz. Malç ayrıca yabani otları kontrol eder. Malç kalınlığı 5-10 cm olmalıdır. Kök boğazı çevresinde malç bırakın - direkt temas ettirmeyin. Malç zamanla ayrışır ve toprağa organik madde sağlar. Siyah malç toprak sıcaklığını artırır, açık renkli malç ise düşürür. Yaz aylarında açık renkli malç tercih edilmelidir. Malç toprak yüzeyini kaplayarak buharlaşmayı %50-70 azaltır.</p><h3>Hastalık Kontrolü: Önleyici Tedbirler</h3><p>Yaz aylarında mantar hastalıkları artar. İyi havalandırma sağlayın ve önleyici tedbirler alın. Yapraklara su değdirmemeye dikkat edin. Bitkiler arası mesafeyi koruyun. Düzenli kontrol yapın ve erken müdahale edin. Organik fungisitler kullanın. Hastalıklı yaprakları hemen temizleyin. Rotasyon sistemi uygulayın. Dayanıklı çeşitler seçmek hastalık riskini azaltır. Yaprakların gece nemli kalmasını önlemek için sabah sulama yapın. İyi havalandırma mantar sporlarının yayılmasını engeller.</p>',
  featured_image = 'https://images.unsplash.com/photo-1466692476868-aef1dfb1e735?q=80&w=2070'
WHERE slug = 'yaz-aylarinda-fide-bakimi-sicak-havalarda-dikkat-edilecekler';

-- 19. SONBAHAR BAHÇE HAZIRLIĞI
UPDATE blogs SET
  excerpt = 'Sonbahar bahçe bakımı nasıl yapılır? Fideleri kışa hazırlama, toprak işleme, kış bitkileri ekimi, alet temizliği ve gelecek sezon için planlama hakkında detaylı rehber.',
  content = '<h2>Sonbahar Bahçe Hazırlığı: Kışa Geçiş</h2><p>Sonbahar, bahçenizi kışa hazırlama ve gelecek sezon için planlama zamanıdır. Doğru hazırlık ile bahara iyi başlarsınız. Sonbahar bakımı, bahçenizin gelecek sezon sağlıklı ve verimli olmasını sağlar. Bu rehberde sonbahar bahçe hazırlığı konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Son Hasatlar: Sezon Sonu Toplama</h3><p>Kışa dayanıklı olmayan bitkileri hasat edin. Olgun meyve ve sebzeleri toplayın. Sonbahar sonunda kalan meyveleri toplayın. Yeşil domatesleri toplayıp olgunlaştırabilirsiniz. Hasat edilmemiş meyveler bitkilerde kalırsa çürüyebilir ve hastalık kaynağı olur. Sonbahar hasadından sonra bitkileri temizleyin. Ölü veya hastalıklı bitki parçalarını çıkarın. Sonbahar sonunda bahçe temizliği yapın. Hasat kayıtlarını tutun - hangi çeşitler iyi yetişti, hangileri sorun çıkardı not edin.</p><h3>Toprak İşleme: Gelecek Sezon İçin Hazırlık</h3><p>Toprağı sürün ve organik gübre ekleyin. Kış boyunca toprak dinlenecek ve besin değerini artıracaktır. Sonbahar toprak işleme, toprak yapısını iyileştirir ve organik maddenin ayrışmasını sağlar. Kompost veya iyi çürümüş gübre ekleyin. Toprak analizi yaptırın ve eksik besin maddelerini belirleyin. Toprak yüzeyini düzleyin. Sonbahar gübrelemesi toprağın kış boyunca besin depolamasını sağlar. Toprak yapısını iyileştirmek için perlit veya kum eklenebilir. Sonbahar toprak işleme bahar dikimini kolaylaştırır.</p><h3>Kış Bitkileri: Soğuğa Dayanıklı Seçenekler</h3><p>Ispanak, lahana, pazı gibi kışa dayanıklı bitkiler ekin. Bu bitkiler kış aylarında da yetişir. Sonbahar başında ekilen kış bitkileri ilkbahara kadar hasat edilebilir. Kış bitkileri için sonbahar ekim zamanı kritiktir. Bitkilerin kış öncesi kök gelişimini tamamlaması gerekir. Kış bitkileri soğuk havalarda lezzetlenir. Koruma önlemleri ile kış boyunca taze sebze hasat edebilirsiniz. Örtü veya küçük seralar kullanarak soğuktan koruyabilirsiniz. Kış bitkileri az bakım gerektirir ve dayanıklıdır.</p><h3>Alet Temizliği ve Depolama</h3><p>Bahçe aletlerini temizleyin ve saklayın. Aletleri su ve sabunla yıkayın, paslanmayı önlemek için yağlayın. Saksıları yıkayın ve gelecek sezon için hazırlayın. Eski toprağı temizleyin ve dezenfekte edin. Aletlerin kış boyunca korunması önemlidir. Kırık veya hasarlı aletleri tamir edin veya değiştirin. Aletleri kuru bir yerde saklayın. Sulama sistemlerini temizleyin ve kış için kapatın. Bahçe aletlerinin bakımı uzun ömürlü olmalarını sağlar.</p><h3>Gelecek Sezon Planlaması</h3><p>Sonbahar, gelecek sezon için planlama zamanıdır. Bu sezon ne iyi yetişti, ne sorun çıkardı not edin. Bahçe düzeni ve rotasyon planınızı gözden geçirin. Yeni bitki çeşitleri araştırın. Tohum ve fide kataloglarını inceleyin. Bahçe planınızı çizin. Sonbahar planlaması bahar başında hızlı başlangıç sağlar. Deneyimlerinizi not edin - bu gelecek sezonlar için çok değerlidir.</p>',
  featured_image = 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=2070'
WHERE slug = 'sonbahar-bahce-hazirligi-kisa-hazirlik-rehberi';

-- 20. KIŞ AYLARINDA BAHÇE
UPDATE blogs SET
  excerpt = 'Kış aylarında fide yetiştirme rehberi. Serada, balkonda ve iç mekanda kış bahçeciliği yapmanın yolları. Soğuğa dayanıklı bitkiler, koruma yöntemleri ve kış bakımı ipuçları.',
  content = '<h2>Kış Bahçeciliği: Yıl Boyunca Üretim</h2><p>Kış aylarında da bahçecilik yapılabilir. Doğru yöntemlerle kış boyunca taze sebze üretebilirsiniz. Kış bahçeciliği, serin iklim bitkileri ve koruma teknikleri ile mümkündür. Bu rehberde kış aylarında bahçecilik konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Sera Kullanımı: Soğuktan Koruma</h3><p>Küçük sera veya cam kutu kullanarak bitkilerinizi soğuktan koruyun. Sera içi sıcaklığı düzenleyin. Serada sıcaklık gündüz yükselir, gece düşer. Havalandırma önemlidir - aşırı ısınmayı önlemek için kapı ve pencereleri açın. Küçük seralar balkon ve teraslarda kullanılabilir. Sera içinde toprak sıcaklığı korunur ve bitkiler büyümeye devam eder. Sera kullanımı kış aylarında 4-6 hafta ek büyüme sağlar. Sera içinde nem kontrolü önemlidir - fazla nem mantar hastalıklarına yol açar. Geceleri sera içi sıcaklığını korumak için örtü kullanabilirsiniz.</p><h3>İç Mekan Yetiştirme: Ev Bahçesi</h3><p>Yeşillikler ve bazı sebzeler iç mekanda yetiştirilebilir. Yeterli ışık ve sıcaklık sağlayın. Güneye bakan pencereler en iyi ışık kaynağıdır. Yapay ışık kullanarak iç mekan bahçeciliğini destekleyebilirsiniz. LED bitki ışıkları iç mekan bahçeciliği için idealdir. Işık kaynağı bitkilere 15-30 cm mesafede olmalıdır. Günlük 12-14 saat ışık yeterlidir. İç mekanda yetiştirme için saksılar ve altlıklar kullanın. Drenaj için altlık kullanın. İç mekan bitkileri daha az su ister - toprak nemini kontrol edin. İç mekanda marul, roka, maydanoz, fesleğen gibi bitkiler kolayca yetiştirilebilir.</p><h3>Kış Bitkileri: Soğuğa Dayanıklı Seçenekler</h3><p>Ispanak, roka, lahana gibi soğuğa dayanıklı bitkiler seçin. Bu bitkiler kış aylarında da büyür. Kış bitkileri hafif dona dayanır. Koruma önlemleri ile daha ağır donlardan korunabilirler. Kış bitkileri için sonbahar ekimi idealdir. Bitkiler kış öncesi kök gelişimini tamamlamalıdır. Kış bitkileri serin havalarda lezzetlenir. Don öncesi bitkileri örtün. Kış boyunca koruma önlemleri ile sürekli hasat yapabilirsiniz. Kış bitkileri az bakım gerektirir ve dayanıklıdır.</p><h3>Koruma: Don Tehlikesinden Korunma</h3><p>Don tehlikesi olan gecelerde bitkilerinizi örtün. Saman, yaprak veya örtü kullanın. Örtü bitkiyi tamamen kaplamalıdır ancak bitkiye baskı yapmamalıdır. Don öncesi bitkileri sulayın - nemli toprak dona karşı daha dayanıklıdır. Saksı bitkilerini iç mekana veya korunaklı yere taşıyın. Don öncesi örtü kurulumu yapın. Sabah örtüyü kaldırın. Don koruması kritik gecelerde bitki ölümünü önler. Dayanıklı çeşitler seçmek don riskini azaltır.</p>',
  featured_image = 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?q=80&w=2070'
WHERE slug = 'kis-aylarinda-bahce-serada-ve-ic-mekanda-yetistirme';

-- PARÇA 4 TAMAMLANDI (Blog 16-20)




