-- ============================================
-- BLOG GÜNCELLEMELERİ - PARÇA 3/6
-- Blog 11-15: Detaylı içerikler ve konuya uygun resimler
-- ============================================
-- Bu SQL dosyasını Supabase Dashboard > SQL Editor'de çalıştırın

-- 11. FİDE HASTALIKLARI VE ÇÖZÜMLERİ
UPDATE blogs SET
  excerpt = 'Fide hastalıkları nasıl önlenir? Yaprak sararması, kök çürümesi, mantar hastalıkları ve zararlı böcekler için organik çözümler. Önleme ve tedavi yöntemleri hakkında detaylı rehber.',
  content = '<h2>Fide Hastalıkları: Önleme ve Tedavi Rehberi</h2><p>Hastalıklar, fide yetiştiriciliğinde en büyük tehditlerden biridir. Önleme, tedaviden daha kolay ve etkilidir. Hastalıklar bitkilerin verimini düşürür ve hatta bitki ölümüne neden olabilir. Bu rehberde fide hastalıkları ve çözümleri hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Yaygın Hastalıklar ve Belirtileri</h3><p><strong>Mantar hastalıkları:</strong> Yapraklarda beyaz, gri veya kahverengi lekeler görülür. İyi havalandırma ile önlenir. Mantar hastalıkları nemli ve sıcak ortamlarda yayılır. Yaprak yüzeyinde toz gibi beyaz bir tabaka görülmesi külleme hastalığını gösterir. Yaprak lekesi hastalığında yapraklarda kahverengi veya siyah lekeler oluşur. Kök çürüklüğü hastalığında bitkiler solar ve kökler kahverengiye döner.</p><p><strong>Kök çürümesi:</strong> Toprak fazla nemli olduğunda görülür. Doğru sulama ile kontrol edilir. Kök çürümesi genellikle aşırı sulama veya kötü drenaj nedeniyle oluşur. Hastalıklı bitkilerin kökleri yumuşak ve kahverengidir. Kök çürümesi durumunda bitkiyi kurtarmak zor olabilir. Önleme için iyi drenaj sağlayın ve aşırı sulamadan kaçının.</p><p><strong>Yaprak lekeleri:</strong> Yapraklarda renk değişiklikleri ve ölü alanlar görülür. Organik fungisitlerle tedavi edilir. Bakteriyel yaprak lekesi yapraklarda su lekeli görünüm oluşturur. Fungal yaprak lekesi ise yapraklarda kahverengi veya siyah lekeler bırakır. Hastalıklı yaprakları hemen temizleyin ve bitkiden uzaklaştırın.</p><h3>Önleyici Tedbirler</h3><p>Sağlıklı fideler seçin, temiz toprak kullanın, bitkiler arası mesafeyi koruyun ve iyi havalandırma sağlayın. Hastalıklı bitkilerden tohum veya fide almayın. Toprak drenajını iyileştirin. Bitkileri düzenli olarak kontrol edin ve erken müdahale yapın. Rotasyon sistemi uygulayın - aynı yerde üst üste aynı bitki türünü yetiştirmeyin. Dayanıklı çeşitler seçmek hastalık riskini azaltır. Bitkileri doğru besleyin çünkü yetersiz beslenme hastalıklara karşı direnci düşürür.</p><h3>Organik Çözümler ve Tedaviler</h3><p>Karbonat çözeltisi, sarımsak suyu ve neem yağı gibi doğal yöntemler hastalıkları kontrol altında tutar. Karbonat çözeltisi (1 litre suya 1 çay kaşığı karbonat) külleme hastalığı için etkilidir. Sarımsak suyu spreyi doğal bir fungisittir. Neem yağı zararlıları ve bazı mantar hastalıklarını kontrol eder. Organik fungisitleri düzenli aralıklarla uygulayın. Hastalıklı yaprakları ve bitki parçalarını hemen temizleyin. Ağır hastalık durumunda bitkiyi tamamen çıkarın ve toprağı dezenfekte edin. Organik çözümler çevre dostudur ve insan sağlığına zararsızdır.</p>',
  featured_image = 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?q=80&w=2070'
WHERE slug = 'fide-hastaliklari-ve-cozumleri-onleme-ve-tedavi';

-- 12. ZARARLI BÖCEKLERLE MÜCADELE
UPDATE blogs SET
  excerpt = 'Bahçedeki zararlı böceklerden nasıl kurtulunur? Yaprak bitleri, örümcek akarı, beyaz sinek ve diğer zararlılar için doğal mücadele yöntemleri. Organik çözümler ve önleyici tedbirler.',
  content = '<h2>Zararlı Böceklerle Mücadele: Doğal Çözümler</h2><p>Zararlı böcekler, fidelerin sağlığını tehdit eder. Organik yöntemlerle etkili mücadele mümkündür. Zararlılar bitkilerin yapraklarını, köklerini ve meyvelerini tahrip eder. Bu rehberde zararlı böceklerle organik mücadele yöntemleri hakkında bilmeniz gereken her şeyi bulacaksınız.</p><h3>Yaygın Zararlılar ve Zararları</h3><p><strong>Yaprak bitleri:</strong> Yapışkan yapraklara neden olur. Küçük yeşil, siyah veya kahverengi böceklerdir. Yaprakların altında ve yeni sürgünlerde bulunur. Yaprak bitleri bitki özünü emerek zayıflatır. Salgıladıkları tatlı madde yapraklarda yapışkan bir tabaka oluşturur ve karınca çeker. Yoğun yaprak biti istilası bitki ölümüne yol açabilir.</p><p><strong>Örümcek akarı:</strong> İnce ağlar oluşturur. Yaprak altında küçük noktalar halinde görünür. Yaprakları emerek sararmasına neden olur. Örümcek akarı kuru ve sıcak koşullarda yayılır. Yapraklarda sarı benekler ve ince ağlar görülmesi örümcek akarı varlığını gösterir. Ağır istilalar yaprakların dökülmesine neden olur.</p><p><strong>Beyaz sinek:</strong> Yapraklarda sararmaya yol açar. Küçük beyaz kanatlı böceklerdir. Yaprak altında yoğun olarak bulunur. Beyaz sinek bitki özünü emerek zayıflatır ve virüs taşıyıcı olabilir. Yaprakları salladığınızda beyaz bulut gibi uçarlar. Salgıladıkları madde yapraklarda mantar oluşumuna yol açar.</p><p><strong>Salyangoz ve sümüklü böcek:</strong> Yaprakları ve meyveleri yerler. Nemli ve serin koşullarda yayılırlar. Genellikle geceleri aktif olurlar. Salyangozlar bitkilerin yumuşak kısımlarını tercih ederler. Ağır istilalar bitkileri tamamen yok edebilir.</p><h3>Organik Çözümler ve Uygulamalar</h3><p>Neem yağı spreyi, sabunlu su çözeltisi ve yararlı böcekler (ladybug) kullanarak zararlıları kontrol edin. Neem yağı hem zararlıları uzaklaştırır hem de bitkileri güçlendirir. Sabunlu su çözeltisi (1 litre suya 1 çay kaşığı organik sıvı sabun) yaprak bitleri ve diğer yumuşak gövdeli zararlılar için etkilidir. Yararlı böcekler zararlıları doğal olarak kontrol eder. Uçucu yağlar (lavanta, nane) zararlıları uzaklaştırır. Organik insektisitleri düzenli aralıklarla uygulayın. Spreyleri sabah erken saatlerde yapın. Tüm yaprak yüzeylerini kaplayın, özellikle yaprak altlarını unutmayın.</p><h3>Önleyici Tedbirler ve Kültürel Uygulamalar</h3><p>Bitkileri düzenli kontrol edin, hastalıklı yaprakları hemen temizleyin ve doğal predatörleri çekmek için çiçek dikin. Bitkiler arası mesafeyi koruyarak hava sirkülasyonunu sağlayın. Yabani otları temizleyin çünkü zararlılar için saklanma yeri oluşturur. Güçlü ve sağlıklı bitkiler zararlılara karşı daha dirençlidir. Rotasyon sistemi uygulayın. Sarı yapışkan tuzaklar beyaz sinek ve yaprak bitlerini yakalar. Fiziksel bariyerler (örgü ağı) zararlıları uzakta tutar. Bahçe temizliği önemlidir - dökülen yaprakları ve bitki artıklarını temizleyin.</p>',
  featured_image = 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?q=80&w=2070'
WHERE slug = 'zararli-boceklerle-mucadele-organik-yontemler';

-- 13. MARUL VE YEŞİLLİK YETİŞTİRME
UPDATE blogs SET
  excerpt = 'Marul, roka, maydanoz ve diğer yeşillikler nasıl yetiştirilir? Hızlı büyüyen yeşillikler için pratik ipuçları, bakım yöntemleri, hasat teknikleri ve kış yetiştiriciliği hakkında detaylı rehber.',
  content = '<h2>Marul ve Yeşillik Yetiştirme: Hızlı Hasat Rehberi</h2><p>Yeşillikler, hızlı büyüyen ve kolay yetiştirilen bitkilerdir. Küçük alanlarda bile bol miktarda üretim yapılabilir. Yeşillikler, ev bahçeciliğinde en kolay başlanacak bitkiler arasındadır. Bu rehberde marul ve diğer yeşillikleri yetiştirme konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Marul Yetiştirme: Detaylı Kılavuz</h3><p>Marul, serin havaları sever. Direkt güneş yerine yarı gölge alanlar tercih edilmelidir. 4-6 hafta içinde hasat edilebilir. Marul tohumlarını direkt toprağa ekebilir veya fide olarak kullanabilirsiniz. Tohumlar çok küçük olduğu için ince bir toprak tabakasıyla örtün. Marul çeşitleri arasında baş salata, yaprak salata, romaine ve butterhead bulunur. Her çeşit farklı lezzet ve dokuya sahiptir. Marul fideleri arasında 20-30 cm mesafe bırakın. Toprak sürekli nemli tutulmalıdır. Marul yetersiz sulama durumunda acılaşır. Yaprakları hasat ederken dıştan başlayın, böylece bitki büyümeye devam eder.</p><h3>Roka ve Maydanoz Yetiştirme</h3><p>Bu bitkiler daha az bakım gerektirir. Düzenli sulama yeterlidir. Roka hızlı büyür ve 3-4 hafta içinde hasat edilebilir. Keskin bir lezzete sahiptir ve salatalarda kullanılır. Roka tohumlarını direkt toprağa ekebilirsiniz. Maydanoz hem yaprak hem de kök olarak kullanılabilir. Maydanoz tohumları yavaş çimlenir, bu nedenle sabırlı olun. Her iki bitki de yarı gölgede iyi yetişir. Hasat için yaprakları dıştan içe toplayın. Düzenli hasat yeni yaprak oluşumunu teşvik eder. Her iki bitki de kış aylarında bile yetiştirilebilir.</p><h3>Kış Yeşillikleri: Soğuğa Dayanıklı Çeşitler</h3><p>Ispanak, lahana ve pazı gibi bitkiler kış aylarında da yetiştirilebilir. Soğuğa dayanıklı çeşitler seçin. Ispanak kış aylarında mükemmel yetişir ve hafif dona dayanır. Lahana çeşitleri soğuk havalarda lezzetlenir. Pazı hem yaprakları hem de sapları için yetiştirilir. Bu bitkiler serin havalarda daha iyi gelişir. Kış yeşillikleri için ekim zamanı sonbahar başıdır. Koruma önlemleri ile kış boyunca taze yeşillik hasat edebilirsiniz. Örtü veya küçük seralar kullanarak soğuktan koruyabilirsiniz.</p><h3>Genel Bakım ve Hasat Teknikleri</h3><p>Yeşillikler hızlı büyüdüğü için düzenli sulama gereklidir. Toprak nemli tutulmalıdır. Hafif gübreleme yeterlidir - aşırı azot yaprakları acılaştırabilir. Yaprakları hasat ederken dıştan başlayın. Bitkinin merkezini koruyarak sürekli hasat yapabilirsiniz. Hasat sonrası yaprakları hemen kullanın veya buzdolabında saklayın. Yeşillikler hassastır ve hızla bozulur. Hasat için sabah erken saatleri tercih edin. Yeşillikler çiçek açmaya başladığında lezzeti acılaşır, bu nedenle çiçek tomurcuklarını hemen kesin.</p>',
  featured_image = 'https://images.unsplash.com/photo-1622206151226-18ca2c9ab4a1?q=80&w=2070'
WHERE slug = 'marul-ve-yesillik-yetistirme-hizli-hasat-rehberi';

-- 14. KABAK YETİŞTİRME
UPDATE blogs SET
  excerpt = 'Kabak fidesi nasıl yetiştirilir? Balkon ve bahçe koşullarında kabak yetiştirmenin püf noktaları, sulama, gübreleme, tozlaşma ve hasat rehberi. Verimli kabak yetiştirme teknikleri.',
  content = '<h2>Kabak Yetiştirme: Yaz Sebzelerinin Verimli Seçeneği</h2><p>Kabak, yaz aylarının en verimli sebzelerinden biridir. Doğru bakımla bir bitkiden onlarca meyve alınabilir. Kabak hem çiçekleri hem de meyveleri için yetiştirilir. Bu rehberde kabak yetiştirme konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Dikim ve Yerleşim: Yeterli Alan Şart</h3><p>Kabak fidelerini geniş saksılara veya bahçe toprağına dikin. Her fide için en az 50x50 cm alan gereklidir. Kabak bitkisi geniş yapraklara sahiptir ve yayılır. Saksı kullanıyorsanız minimum 30 litre kapasiteli olmalıdır. Fideler arasında yeterli mesafe bırakın. Kabak bitkileri hızlı büyür ve yaprakları çok genişler. Dikim sırasında kök sistemine dikkat edin. Kabak fideleri hassastır, bu nedenle dikkatli taşıyın. Dikim sonrası bolca su verin.</p><h3>Su İhtiyacı: Bol ve Düzenli Sulama</h3><p>Kabak çok su sever. Özellikle meyve tutumundan sonra düzenli ve bol sulama şarttır. Toprak sürekli nemli tutulmalıdır. Yapraklar altına su vermeyin çünkü bu mantar hastalıklarını tetikler. Kök çevresine su verin. Yetersiz sulama meyve dökülmesine neden olur. Sıcak yaz günlerinde günde iki kez sulama gerekebilir. Toprak yüzeyine malç sererek su kaybını önleyebilirsiniz. Kabak yaprakları büyük olduğu için su kaybı fazladır. Düzenli sulama meyve kalitesini artırır.</p><h3>Tozlaşma: Verim İçin Kritik</h3><p>Meyve tutumu için arılar gereklidir. Çiçek açan bitkiler dikerek arıları bahçenize çekin. Kabak bitkilerinde hem erkek hem de dişi çiçekler vardır. Dişi çiçeklerin altında küçük meyve görünümü vardır. Arılar çiçekler arasında polen taşıyarak tozlaşmayı sağlar. Yeterli arı yoksa elle tozlaşma yapabilirsiniz. Erkek çiçekten polen alıp dişi çiçeğin ortasına sürün. Tozlaşma genellikle sabah erken saatlerde gerçekleşir. Çiçekler açıldığında tozlaşma yapılmalıdır. Tozlaşma başarılı olursa dişi çiçek altındaki meyve büyümeye başlar.</p><h3>Gübreleme ve Bakım</h3><p>Kabak hızlı büyüyen bir bitkidir ve düzenli beslenme ister. Dikim öncesi toprağa organik gübre karıştırın. Çiçeklenme döneminde potasyum ağırlıklı gübre kullanın. Her 2 haftada bir sıvı organik gübre ile destekleyin. Yapraklar sararmaya başlarsa azot eksikliği olabilir. Kabak bitkileri büyük yapraklar geliştirir, bu nedenle yeterli beslenme önemlidir. Yabani otları düzenli olarak temizleyin. Yapraklar çok büyüdüğünde alt yaprakları budayabilirsiniz.</p><h3>Hasat: Küçükken Hasat Edin</h3><p>Kabakları küçükken hasat edin. 15-20 cm boyunda toplayın. Genç kabaklar daha lezzetli ve daha az çekirdeklidir. Büyük meyveler yeni meyve oluşumunu engeller. Düzenli hasat verimi artırır. Hasat sırasında meyveyi sapından tutup makasla kesin. Kabakları buzdolabında 1 haftaya kadar saklayabilirsiniz. Çiçekler de yenilebilir - dolması veya kızartması yapılır. Çiçekleri sabah erken saatlerde hasat edin. Taze çiçekler daha lezzetlidir. Sezon boyunca düzenli hasat yaparak sürekli ürün alabilirsiniz.</p>',
  featured_image = 'https://images.unsplash.com/photo-1592496431122-2349e0fbc666?q=80&w=2070'
WHERE slug = 'kabak-yetistirme-balkonda-ve-bahcede-basarı-ipuclari';

-- 15. SOĞAN VE SARIMSAK YETİŞTİRME
UPDATE blogs SET
  excerpt = 'Soğan ve sarımsak nasıl yetiştirilir? Soğan seti, sarımsak dişi ekimi, bakımı, kış yetiştiriciliği ve hasat teknikleri hakkında detaylı bilgiler. Uzun süreli saklama yöntemleri.',
  content = '<h2>Soğan ve Sarımsak Yetiştirme: Bahçenin Temel Ürünleri</h2><p>Soğan ve sarımsak, bahçenizin temel ürünleridir. Kolay yetiştirilir, uzun süre saklanabilir ve mutfağınızın vazgeçilmez malzemeleridir. Her iki bitki de kış aylarında yetiştirilebilir ve düşük bakım gerektirir. Bu rehberde soğan ve sarımsak yetiştirme konusunda bilmeniz gereken her şeyi bulacaksınız.</p><h3>Soğan Seti Ekip: Kolay Başlangıç</h3><p>Soğan setlerini ilkbahar veya sonbaharda toprağa dikin. Soğan setleri küçük soğanlardır ve hızlı büyüme sağlar. 10-15 cm aralıklarla yerleştirin. Üst kısmı toprak üzerinde kalmalıdır - soğan setini tamamen gömmeyin. Dikim sırasında kök tarafını aşağı, üst kısmını yukarı gelecek şekilde yerleştirin. Soğan setleri tohumdan daha hızlı büyür. Toprak sıcaklığı 10°C''nin üzerinde olmalıdır. Dikim sonrası hafifçe sulayın. Soğan setleri 2-3 hafta içinde yeşil yapraklar çıkarır. İlk birkaç hafta düzenli sulama yapın ancak aşırıya kaçmayın.</p><h3>Sarımsak Dikimi: Sonbahar Ekimi</h3><p>Sarımsak dişlerini sonbaharda dikin. Sarımsak soğuk hava gerektirir ve kış aylarında kök gelişimi yapar. İlkbaharda yeşil yapraklar çıkar. Her sarımsak dişini ayrı ayrı dikin. Dişlerin sivri ucu yukarı, kök tarafı aşağı gelecek şekilde yerleştirin. 10-15 cm derinliğe ve 15-20 cm aralıklarla dikin. Sarımsak dişlerini ayırırken zar kağıdına dikkat edin - zararlı olabilir. Sonbahar dikimi daha büyük sarımsak başları verir. Kış boyunca kök sistemi gelişir ve ilkbaharda hızlı büyüme başlar. Don riski olan bölgelerde sarımsakları saman veya yaprakla örtün.</p><h3>Bakım ve Gübreleme</h3><p>Düzenli sulama yapın ama aşırıya kaçmayın. Soğan ve sarımsak çok fazla su istemez. Yabani otları temizleyin - otlar bu bitkilerle rekabet eder. Gübreleme az miktarda yeterlidir. Aşırı azot yaprak gelişimini artırır ama soğan başı oluşumunu engelleyebilir. Çiçek sapları görürseniz hemen kesin - çiçeklenme soğan gelişimini durdurur. Toprak yüzeyine malç sererek yabani otları kontrol edebilir ve toprak nemini koruyabilirsiniz. Soğan ve sarımsak yaprakları solmaya başladığında sulamayı azaltın. Bu, başların olgunlaşmasını sağlar.</p><h3>Hasat ve Saklama: Uzun Ömürlü Depolama</h3><p>Yapraklar sararınca ve yarı yarıya kuruyunca soğan ve sarımsakları sökün. Hasat zamanı yaprakların doğal olarak sararması ve yere yatmasıdır. Hasat için kuru bir gün seçin. Soğan ve sarımsakları topraktan çıkarın ve toprağı temizleyin. Serin, kuru ve havalandırılmış bir yerde 2-3 hafta kurutun. Kurutma sırasında yaprakları kesmeyin - kurumalarına izin verin. Tam kuruduktan sonra yaprakları kesin ve saklayın. Soğan ve sarımsakları file torbalarda veya örgü sepetlerde saklayın. Serin (4-10°C), kuru ve karanlık bir yer idealdir. Doğru şekilde saklanırsa 6-12 ay taze kalabilirler. Hasarlı veya hastalıklı olanları ayırın ve hemen kullanın.</p>',
  featured_image = 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?q=80&w=2070'
WHERE slug = 'sogan-ve-sarimsak-yetistirme-baslangic-rehberi';

-- PARÇA 3 TAMAMLANDI (Blog 11-15)



